### ISSUE TITLE
堂哥，单独用x5webView的时候没问题，但是项目中有其他ABIs时就会找不到

### ISSUE THREAD

**Issue by Jetereting** [MiQt/X5WebView#2]
我的项目里有arm64-v8a的.so
![image](https://cloud.githubusercontent.com/assets/11585188/21953956/a1b161e0-da7f-11e6-9f52-b109f43a6041.png)
堂哥这里只有armeabi的.so
![image](https://cloud.githubusercontent.com/assets/11585188/21953968/dc9b09aa-da7f-11e6-9bc1-df831b5ff12c.png)
所以在arm64-v8a的机子上找不到，我试图删除了我项目的arm64-v8a (里面有个腾讯地图的.so)结果定不了位了，参考的 https://zhuanlan.zhihu.com/p/23102158  请问还有什么解决方案？比如您那边加上不同cpu的.so 希望能得到您的指点，另外新年快乐~

**Comment by Jetereting** [comment]
解决了，解决了，abiFilters改成abiFilters "armeabi", "armeabi-v7a", "x86"就行~

**Comment by Jetereting** [comment]
新年快乐~

**Comment by iielse** [comment]
你这个解决方法不算解决问题，算规避问题。解决方法应该是 堂哥 把 so 配齐， 由开发使用者自己来决定使用啥。 而不是 三方功能jar包决定开发者使用啥
@Jetereting

**Comment by iielse** [comment]
结果官网tm的只有一个so

**Comment by iielse** [comment]
结果官网的so 还是 copy来的
